[package]
name = "mediawiki"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]
edition = "2018"

[dependencies]
cookie = "0.12"
regex = "1.0"
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
debug = true
