[package]
name = "mediawiki"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]

[dependencies]
cookie = { default-features = false, version = "0.10" }
regex = "1.0"
reqwest = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[profile.release]
debug = true
