[package]
name = "mediawiki"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]
[profile.release]
debug = true
[dependencies]
cookie = { default-features = false, version = "0.7" }
hyper = "0.10"
regex = "0.2"
rustc-serialize = "0.3"
url = "1.4"
