name: Rust
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain: [nightly]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        default: true
        profile: minimal
        components: clippy, rustfmt
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Clippy
      run: cargo clippy
    - name: Check formatting
      run: cargo fmt -- --check
